version: 2.1
orbs:
  eventuate-gradle-build-and-test: "eventuate_io/eventuate-gradle-build-and-test@0.2.1"
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - eventuate-gradle-build-and-test/build-and-test:
          name: mysql-binlog-intel
          script: ./gradlew testClasses
      - eventuate-gradle-build-and-test/build-and-test:
          name: mysql-binlog-arm
          resource_class: arm.medium
          script: ./gradlew testClasses
